export const SET_QUIZZES = 'SET_QUIZZES';
export const ADD_QUIZ = 'ADD_QUIZ';
export const REMOVE_QUIZ = 'REMOVE_QUIZ';
export const REMOVE_TERM_FROM_QUIZ = 'REMOVE_TERM_FROM_QUIZ';
export const SET_QUIZ_TERM_IDS = 'SET_QUIZ_TERM_IDS';